name: Eriks POC

on: [push]

jobs:
  list_contents:
     runs-on: [yocto_build]
     steps:
        # Steps for heavy tasks here
       - name: Init repo
         run: repo init -u ssh://rev.homesmart.ninja:29418/ikeix/manifest 

       - name: Repo sync
         run: repo sync --force-sync --fail-fast -cq 

       - name: Make doc
         run: cd nexus && make doc 
