on: [push]

jobs:
  list_contents:
     runs-on: [yocto_build]
     steps:
        # Steps for heavy tasks here
       - name: List contents of the repository directory
         run: git clone "ssh://rev.homesmart.ninja:29418/devices/doc" 
